spring.datasource.url=jdbc:h2:file:./data/study-log;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
logging.level.org.hibernate.SQL=debug
