-- 지금까지 `ddl-auto=update` 가 만들어 온 스키마를 그대로 옮긴 기준선.
--
-- 08-11 당시 이미 돌고 있던 볼륨에는 이 파일이 실행되지 않았다 — `baseline-on-migrate` 가
-- 비어 있지 않은 스키마를 버전 1 로 표시하고 넘어갔기 때문이다(그 설정은 08-14 에 걷었고,
-- 지금 이 파일이 도는 곳은 빈 DB 뿐이다). 그 볼륨에서는 여기 적힌 것과 실제 스키마가 어긋나면
-- 부팅 시점의 `validate` 가 대신 잡으므로, 컬럼 이름·타입·널 여부는 운영 DB 를
-- `pg_dump --schema-only` 로 떠서 맞췄다.
--
-- 실측으로 두 스키마의 컬럼 17개가 이름·타입·널 여부까지 같고, 갈리는 것은 둘뿐이다.
--   * 제약 이름 — 옛 볼륨에는 하이버네이트가 만든 해시(`fk7xajbeidwityc1bqfusswp8a0`)가 남는다
--   * 컬럼 순서 — 하이버네이트는 이름순에 FK 를 뒤에 붙이고, 아래는 읽는 순서다
-- `validate` 도 질의도 컬럼을 이름으로 찾으므로 둘 다 걸리는 곳이 없다. 읽히는 쪽을 택했다.

create table category (
    id       bigint       generated by default as identity primary key,
    name     varchar(50)  not null,
    -- 대소문자·공백만 다른 분야가 통계를 가르지 않게 하는 최종 방어선.
    -- 이 파일이 생긴 뒤로는 `create unique index ... (lower(name))` 도 쓸 수 있게 됐지만
    -- 그래도 컬럼으로 두는 것은, 키 파생이 소문자화만이 아니라 공백 축약을 함께 하기 때문이다
    -- (`Category.toKey`). `lower(name)` 로는 붙여넣은 전각 공백이 든 분야가 그대로 빠져나간다
    name_key varchar(50)  not null,
    constraint uk_category_name_key unique (name_key)
);

create table study_log (
    id               bigint        generated by default as identity primary key,
    title            varchar(200)  not null,
    study_date       date          not null,
    start_time       time(0)       not null,
    end_time         time(0)       not null,
    -- 저장 시점 파생값. 통계를 열 때마다 기록 전량에서 다시 빼지 않기 위해 컬럼으로 둔다
    duration_minutes integer       not null,
    summary          varchar(500),
    note             text,
    category_id      bigint        not null,
    created_at       timestamp(6)  not null,
    updated_at       timestamp(6)  not null,
    constraint fk_study_log_category foreign key (category_id) references category (id)
);

create index idx_study_log_study_date on study_log (study_date);
create index idx_study_log_category_id on study_log (category_id);

create table study_log_tag (
    study_log_id bigint      not null,
    tag          varchar(50) not null,
    -- 입력 순서를 그대로 되돌려 주는 자리. (study_log_id, tag) 유일 제약을 두지 않는 것은
    -- 자리 맞바꾸기가 플러시 중간에 잠깐 겹치기 때문
    tag_order    integer     not null,
    constraint pk_study_log_tag primary key (study_log_id, tag_order),
    constraint ck_study_log_tag_order check (tag_order >= 0),
    constraint fk_study_log_tag_study_log foreign key (study_log_id) references study_log (id)
);

create index idx_study_log_tag_tag on study_log_tag (tag);
