-- 앞으로 할 공부 체크리스트. 기록(study_log)과 잇지 않으므로 외래 키가 없다.
--
-- 우선순위를 varchar 로 두는 것은 enum 을 ORDINAL 이 아니라 STRING 으로 저장하기 때문이다.
-- 값의 뜻이 상수 선언 순서에 매이지 않는 대신 정렬은 알파벳순이 되므로, 목록 정렬은 SQL 이
-- 아니라 서비스가 자바로 진다.

create table study_plan (
    id           bigint       generated by default as identity primary key,
    title        varchar(200) not null,
    note         varchar(200),
    priority     varchar(10)  not null,
    done         boolean      not null,
    created_at   timestamp(6) not null,
    completed_at timestamp(6),
    -- 애플리케이션이 enum 으로 막고 있는 값이지만, 손으로 넣은 행까지 막는 자리는 여기뿐이다
    constraint ck_study_plan_priority check (priority in ('HIGH', 'NORMAL', 'LOW')),
    -- done 과 completed_at 은 한 사건의 두 표현이다. 한쪽만 바뀐 행은 예외가 아니라 화면의
    -- 빈칸으로 새어 나가므로, 도메인의 toggle() 과 같은 불변식을 저장 계층에도 세운다
    constraint ck_study_plan_completed_at
        check ((done and completed_at is not null) or (not done and completed_at is null))
);

-- 미완료·완료를 따로 조회한다 — 둘의 정렬 규칙이 서로 달라 한 질의로 묶이지 않는다
create index idx_study_plan_done on study_plan (done);
